version: '3.3'
services:

  rabbitmq:
    image: rabbitmq:latest
    container_name: 'rabbitmq'
    ports:
      - 5672:5672

  redis:
    image: redis:latest
    container_name: 'redis'
    command: redis-server --requirepass 'password'

  mongo:
    image: mongo:latest
    container_name: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "mongo"
    ports:
      - 27017:27017

  postgres:
    image: postgres:latest
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  python:
    build: docker/python
    image: python
    container_name: 'python'
    depends_on:
      - redis
      - mysqldb
      - mongo
    environment:
      - DOCKER=True
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=$PYTHONPATH:/code
      - PIPENV_VENV_IN_PROJECT=1
      - SHELL=/bin/bash
    volumes:
      - ./:/code
