version: '3.3'
services:

  beanstalkd:
    build: docker/beanstalkd
    image: beanstalkd
    command: /usr/bin/beanstalkd -b /var/lib/beanstalkd
    ports:
      - 11300:11300

  redis:
    image: redis:latest
    command: redis-server --requirepass 'password'

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "mongo"
    ports:
      - 27017:27017

  mysqldb:
    image: mysql:latest
    command: mysqld --sql_mode=""
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'

  python:
    build: docker/python
    image: python
    container_name: python
    depends_on:
      - beanstalkd
      - redis
      - mysqldb
      - mongo
    environment:
      - DOCKER=True
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=$PYTHONPATH:/code
      - PIPENV_VENV_IN_PROJECT=1
      - SHELL=/bin/bash
    volumes:
      - ./:/code
      - ${SECRETS_PATH:-./config.json}:/code/config.json
      - ~$USER/.cache:/home/python/.cache  # shared cache
  #     - ./var/log:/code/var/log
